# Generated by Django 2.0.6 on 2018-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180624_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='file',
            name='long',
        ),
        migrations.AddField(
            model_name='owner',
            name='login_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
